### ISSUE TITLE
Teradata not recognizing drivers when using conda.

### ISSUE THREAD

**Issue by aborsu** [Teradata/PyTd#108]
I've taken the liberty to create a new issue as the no drivers recognized has a couple of issues open already, but I think the problem comes from the use of a conda install of python rather than a system install (I'm not sure).

When using tdxodbc everything works even from python, but from conda the drivers are not recognized.
I believe that when using conda, it by defaults uses the libodbc.so library that is packaged with conda rather than the system one.
 
``` bash
$ export ODBCINI=/home/users/some_user/odbc.ini
$ export ODBCINST=/home/users/some_user/odbcinst.ini
$ /opt/teradata/client/16.10/bin/tdxodbc64 -C "DRIVER=Teradata; DBCNAME=some_db; UID=some_user; PWD=some_password;"

Connecting with SQLDriverConnect("DRIVER=Teradata; DBCNAME=some_db; UID=some_user; PWD=*;")...

.....ODBC connection successful.


$ ipython
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58)
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: !/opt/teradata/client/16.10/bin/tdxodbc64 -C "DRIVER=Teradata; DBCNAME=some_db; UID=some_user; PWD=some_password;"


Connecting with SQLDriverConnect("DRIVER=Teradata; DBCNAME=some_db; UID=some_user; PWD=*;")...

.....ODBC connection successful.

In [2]: import teradata

In [3]: udaexec = teradata.UdaExec(appName="HelloWorld",
   ...:                            version="1.0",
   ...:                            logConsole=True,
   ...:                            logLevel='DEBUG')
2018-06-21 11:08:03,587 - teradata.udaexec - INFO - Initializing UdaExec...
2018-06-21 11:08:03,587 - teradata.udaexec - INFO - Reading config files: ['/etc/udaexec.ini: Not Found', '/home/users/some_user/udaexec.ini: Not Found', '/home/users/some_user/udaexec.ini: Not Found']
2018-06-21 11:08:03,587 - teradata.udaexec - INFO - Found run number file: "/home/users/some_user/.runNumber"
2018-06-21 11:08:03,587 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2018-06-21 11:08:03,587 - teradata.udaexec - INFO - Removed 0 log files.
2018-06-21 11:08:03,587 - teradata.udaexec - DEBUG - Git path not specified, using system path.
2018-06-21 11:08:03,773 - teradata.udaexec - DEBUG - Git information is not available: fatal: Not a git repository (or any parent up to mount point /home/users)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
.
2018-06-21 11:08:03,784 - teradata.udaexec - INFO - Checkpoint file not found: /home/users/some_user/HelloWorld.checkpoint
2018-06-21 11:08:03,784 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2018-06-21 11:08:03,785 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: HelloWorld
 *          Version: 1.0
 *       Run Number: 20180621110803-121
 *             Host: spal0062
 *         Platform: Linux-2.6.32-696.6.3.el6.x86_64-x86_64-with-redhat-6.6-Santiago
 *          OS User: some_user
 *   Python Version: 3.6.1
 *  Python Compiler: GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
 *     Python Build: ('default', 'May 11 2017 13:09:58')
 *  UdaExec Version: 15.10.0.21
 *     Program Name: /appl/icpy01/opt/customer_analytics/bin/ipython
 *      Working Dir: /home/users/some_user
 *          Log Dir: /home/users/some_user/logs
 *         Log File: /home/users/some_user/logs/HelloWorld.20180621110803-121.log
 *     Config Files: ['/etc/udaexec.ini: Not Found', '/home/users/some_user/udaexec.ini: Not Found', '/home/users/some_user/udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=HelloWorld;Version=1.0;JobID=20180621110803-121;ClientUser=some_user;Production=False;udaAppLogFile=/home/users/some_user/logs/HelloWorld.20180621110803-121.log;UtilityName=PyTd;UtilityVersion=15.10.0.21
********************************************************************************/
2018-06-21 11:08:03,787 - teradata.udaexec - DEBUG - Configuration Details:
/********************************************************************************
 *   appName: HelloWorld
 * runNumber: 20180621110803-121
 *   version: 1.0
********************************************************************************/

In [4]: session = udaexec.connect(method="odbc", DRIVER='Teradata', system="some_db", username="some_user", password="some_password");
2018-06-21 11:08:30,593 - teradata.udaexec - INFO - Creating connection: {'method': 'odbc', 'DRIVER': 'Teradata', 'system': 'some_db', 'username': 'some_user', 'password': 'XXXXXX'}
2018-06-21 11:08:30,604 - teradata.tdodbc - INFO - Loading ODBC Library: libodbc.so
2018-06-21 11:08:30,605 - teradata.tdodbc - INFO - Available drivers:
2018-06-21 11:08:30,606 - teradata.udaexec - ERROR - Unable to create connection: {'method': 'odbc', 'DRIVER': 'Teradata', 'system': 'some_db', 'username': 'some_user', 'password': 'XXXXXX'}
Traceback (most recent call last):
  File "/appl/wrdi01/data/shared/apm/python/lib/python3.6/site-packages/teradata/udaexec.py", line 183, in connect
    **args))
  File "/appl/wrdi01/data/shared/apm/python/lib/python3.6/site-packages/teradata/tdodbc.py", line 427, in __init__
    connectParams["DRIVER"] = determineDriver(dbType, driver)
  File "/appl/wrdi01/data/shared/apm/python/lib/python3.6/site-packages/teradata/tdodbc.py", line 391, in determineDriver
    "Available drivers: {}".format(dbType, ",".join(drivers)))
teradata.api.InterfaceError: ('DRIVER_NOT_FOUND', "No driver found for 'Teradata'.  Available drivers: ")
---------------------------------------------------------------------------
InterfaceError                            Traceback (most recent call last)
<ipython-input-5-d9bf8a0580c4> in <module>()
----> 1 session = udaexec.connect(method="odbc", DRIVER='Teradata', system="some_db", username="some_user", password="some_password");

/appl/wrdi01/data/shared/apm/python/lib/python3.6/site-packages/teradata/udaexec.py in connect(self, externalDSN, dataTypeConverter, **kwargs)
    181                                          odbcLibPath=self.odbcLibPath,
    182                                          dataTypeConverter=dataTypeConverter,
--> 183                                          **args))
    184             else:
    185                 raise api.InterfaceError(

/appl/wrdi01/data/shared/apm/python/lib/python3.6/site-packages/teradata/tdodbc.py in __init__(self, dbType, system, username, password, autoCommit, transactionMode, queryBands, odbcLibPath, dataTypeConverter, driver, **kwargs)
    425         connectParams = collections.OrderedDict()
    426         if "dsn" not in extraParams:
--> 427             connectParams["DRIVER"] = determineDriver(dbType, driver)
    428         if system:
    429             connectParams["DBCNAME"] = system

/appl/wrdi01/data/shared/apm/python/lib/python3.6/site-packages/teradata/tdodbc.py in determineDriver(dbType, driver)
    389                 "DRIVER_NOT_FOUND",
    390                 "No driver found for '{}'.  "
--> 391                 "Available drivers: {}".format(dbType, ",".join(drivers)))
    392         else:
    393             retval = matches[len(matches) - 1]

InterfaceError: ('DRIVER_NOT_FOUND', "No driver found for 'Teradata'.  Available drivers: ")


```

**Comment by msarahan** [comment]
Hi, I work for Anaconda, and we'd like to understand what's going wrong here.  Unfortunately, I don't know enough about Teradata to know what the problem is yet.  It looks to me like ``/opt/teradata/client/16.10/bin/tdxodbc64`` is a binary in a totally separate world - one that presumably finds its own libodbc.  Whatever libodbc we're providing via conda presumably isn't the correct one.  We'd be happy to point the python teradata at the correct one if we knew what it should be - or better yet, how to build a package with the correct one.

**Comment by nehaljwani** [comment]
Another way to mitigate this issue is to pass the argument:
```
session = udaexec.connect(method="odbc", ...  odbcLibPath="/path/to/teradata/libodbc.so" );
```
In OP's case, it would be: `/opt/teradata/client/16.10/lib64/libodbc.so`

**Comment by aborsu** [comment]
@nehaljwani 
I've tried this but it doesn't work either. 
I also have No driver found for Teradata.

**Comment by nehaljwani** [comment]
@aborsu I patched the taradata package and changed the line:
```
odbc = ctypes.cdll.LoadLibrary(odbcLibPath) 
```
to:
```
odbc = ctypes.cdll.LoadLibrary("/absolute/path/to/teradata/driver/provided/libodbc.so") 
```
And now along with ODBCINST and ODBC pointing to the correct ini files provided by the teradata odbc driver package, everything works. I don't even have to remove unixodbc.

**Comment by mrianclarito** [comment]
Hi team,

I am trying the suggested workarounds for the exact same scenario (unixodbc installed and has been removed, trying to pytd module via Anaconda returns "DRIVER_NOT_FOUND") by explicitly defining the libodbc.so actual path inside the tdodbc.py file:

`
def initOdbcLibrary(odbcLibPath=None):
...
odbcLibPath = "/opt/teradata/client/ODBC_64/lib/libodbc.so"
odbc = ctypes.cdll.LoadLibrary(odbcLibPath)
`

Even with this I am still getting the error. I wanted to check if there's a way to debug from the code where it returns the "DRIVER_NOT_FOUND" -- would you have any ideas?
`
def initDriverList():
...
rc = SQL_SUCCESS
...
rc = odbc.SQLDrivers(hEnv, direction, description,
                                   len(description), ADDR(descriptionLength),
                                   None, 0, attributesLength)
#rc returns a value of "100" which is SQL_NO_DATA => DRIVER_NOT_FOUND
`

Thanks.

**Comment by aborsu** [comment]
Hello,

Same thing for me, specifying the odbcLibPath does not resolve the issue.

**Comment by aborsu** [comment]
We switched to the new teradatasql package. No issue anymore

**Comment by HerculesGomez** [comment]
Had the same issue. Tried many of the above but nothing worked. I removed anaconda and installed python36 and it is owkring now on oracle linux.

**This is all I have in my .bash_profile:**
export ODBCINI=/opt/teradata/client/ODBC_64/odbc.ini

**And then the contents of /opt/teradata/client/ODBC_64/odbc.ini are:**
[ODBC Drivers]
Teradata Database ODBC Driver 16.20=Installed

[Teradata Database ODBC Driver 16.20]
Description=Teradata Database ODBC Driver 16.20
Driver=/opt/teradata/client/ODBC_64/lib/tdataodbc_sb64.so
CPTimeout=60

[ODBC]
InstallDir=/opt/teradata/client/ODBC_64
Trace=no
Pooling=yes

[ODBC Data Sources]
Teradata ODBC DSN=Teradata Database ODBC Driver 16.20

[TDP6]
Description=Teradata Database ODBC Driver 16.20

# Driver: The location where the ODBC driver is installed to.
Driver=/opt/teradata/client/ODBC_64/lib/tdataodbc_sb64.so

# Required: These values can also be specified in the connection string.
DBCName1=**<put your teradata ip here>**
UID=
PWD=

Hope this helps!
