### ISSUE TITLE
Error while connecting Teradata using python.

### ISSUE THREAD

**Issue by mraduldhakad1** [Teradata/PyTd#74]
Hi ,
I am getting below while connecting Teradata using Python.
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\hello.py", line 5, in <module>
    session = udaExec.connect(method="odbc", system="xxx",username="xxx", password="xxx!");
  File "C:\Python27\Lib\site-packages\teradata\udaexec.py", line 183, in connect
    **args))
  File "C:\Python27\Lib\site-packages\teradata\tdodbc.py", line 427, in __init__
    connectParams["DRIVER"] = determineDriver(dbType, driver)
  File "C:\Python27\Lib\site-packages\teradata\tdodbc.py", line 391, in determineDriver
    "Available drivers: {}".format(dbType, ",".join(drivers)))
InterfaceError: ('DRIVER_NOT_FOUND', "No driver found for 'Teradata'.  Available drivers: SQL Server,Microsoft ODBC for Oracle,Microsoft Access Driver (*.mdb),Microsoft Access-Treiber (*.mdb),Driver do Microsoft Access (*.mdb),Microsoft dBase Driver (*.dbf),Microsoft dBase-Treiber (*.dbf),Driver do Microsoft dBase (*.dbf),Microsoft Excel Driver (*.xls),Microsoft Excel-Treiber (*.xls),Driver do Microsoft Excel(*.xls),Microsoft Paradox Driver (*.db ),Microsoft Paradox-Treiber (*.db ),Driver do Microsoft Paradox (*.db ),Microsoft Text Driver (*.txt; *.csv),Microsoft Text-Treiber (*.txt; *.csv),Driver da Microsoft para arquivos texto (*.txt; *.csv),Microsoft Visual FoxPro Driver,Microsoft FoxPro VFP Driver (*.dbf),Microsoft dBase VFP Driver (*.dbf),Microsoft Visual FoxPro-Treiber,Driver para o Microsoft Visual FoxPro,SQL Server Native Client 10.0")
I am using below code .
import teradata
import pyodbc
udaExec = teradata.UdaExec (appName="HelloWorld", version="1.0",
        logConsole=True)
session = udaExec.connect(method="odbc", system="xxx",username="xxx", password="xxx!");

could please anyone help me in resolving this error.

**Comment by escheie** [comment]
Looks like the Teradata ODBC Driver Manager is not registered with the Window's ODBC Driver Manager.   Is the Teradata ODBC driver installed?

**Comment by mraduldhakad1** [comment]
Yes it is installed.

**Comment by escheie** [comment]
Okay, then you may want to try uninstalling it and reinstalling it.   It needs to show up in the list of available drivers so the Python module can access it.
